source: src
destination: build

tag_dir: blog/tag

# Site settings
baseurl: ""

# Color settings (Hex value without #)
color_alpha: feeaeb
color_beta: 0f0f0f

# Google Analytics
google_analytics: UAâ€”XXXXXXXX-X

# Instagram API
instagram_key: 1830171761.1677ed0.70847a59233249c79b29005c69209fb6
instagram_caption: false

# SEO settings
title: My Wild Bouquet
description:
url: ""
email: mywildbouquet@gmail.com
twitter_username: mywildbouquet
default_img:

# Profile settings
social:
  twitter: https://twitter.com/mywildbouquet
  instagram: https://www.instagram.com/mywildbouquet/

# Build settings
exclude: ["node_modules", "gulpfile.js", "assets/js/app.js", "README.md", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /blog/:title

# Sass
sass:
  style: compressed

# Gems
gems:
  - jekyll-sitemap
  - octopress-autoprefixer
  - jekyll-redirect-from
